Make CleanPath middleware work with other routers
go-chi/chi pull request #786
Opened 2023-01-27 13:06 UTC by romain-tadiello

The rctx is not checked and could be nil if the function isn't used with a chi.Router. 
It ends up in a panic.

Additional point: the cleaning only happens in the rctx.RoutePath is an empty string. If a function like [GetHead](https://github.com/go-chi/chi/blob/v1.5.4/middleware/get_head.go#L10) [¶](https://pkg.go.dev/github.com/go-chi/chi/middleware#GetHead) is called before it won't clean the path.

2023-02-05 15:54 UTC, pkieltyka requested changes

2023-02-05 15:54 UTC, pkieltyka commented on middleware/clean_path.go
> +		rctx.RoutePath = path.Clean(routePath)
wont it panic on this line if rctx is nil..? and this PR changes the logic of the method as well, calling path.Clean() more often then previously

2024-03-08 00:01 UTC, gangelop commented
in #787 @romain-tadiello says

> Additional point: the cleaning only happens in the rctx.RoutePath is an empty string. If a function like [GetHead](https://github.com/go-chi/chi/blob/v1.5.4/middleware/get_head.go#L10) [¶](https://pkg.go.dev/github.com/go-chi/chi/middleware#GetHead) is called before it won't clean the path.

I'm not sure but this might be relevant to why he moved the `path.Clean()` out of the conditional.
Apologies if that's not relevant. I literally just started using chi today.

2024-09-18 20:10 UTC, VojtechVitek commented
For reference, this is similar fix to https://github.com/go-chi/chi/pull/841 but in a different MW.

@romain-tadiello Closing due to inactivity. Feel free to reopen the PR if you plan to address the above comment.

2024-09-18 20:10 UTC, closed without merging