ClientIP middleware proposal, intended to replace RealIP
go-chi/chi pull request #967
Opened 2024-12-15 21:02 UTC by VojtechVitek

2024-12-16 01:46 UTC, convto approved these changes
I’ve checked the implementation, and I completely agree with the approach.
It addresses the concerns beautifully, and I’m very grateful for the effort put into this!

2025-01-20 20:55 UTC, VojtechVitek commented
> P.S.: This PR uses the "net/netip" package and assumes that we'll accept https://github.com/go-chi/chi/issues/963.

The CI tests are now passing since rebasing against `master`. We can now use `"net/netip"` pkg, since we dropped support for Go 1.19 and older.

@jawnsy @adam-p @convto @Dirbaio @pkieltyka @mfridman @lrstanley @n33pm @c2h5oh

I'd appreciate any more reviews 👀 🙏 .

2025-01-20 20:58 UTC, c2h5oh requested changes

2025-01-20 20:58 UTC, c2h5oh commented on middleware/client_ip.go
> +				}
If trusted prefixes are set then we only care and/or can trust the first value past those trusted prefixes. No loopback, private pr unspecified addresses should exist past trusted prefixes unless headers have been tampered with.

1. Move trusted prefixes check block before this
2. Loopback/private/unspecified check should exit without setting client IP if any trusted prefixes are set

2025-01-20 20:58 UTC, c2h5oh commented on middleware/client_ip.go
> +func ClientIPFromXFFHeader(trustedIPPrefixes ...string) func(http.Handler) http.Handler {
Having `numTrustedProxies` as an alternative to trusted prefixes would be a useful option too. If you control exactly n proxies, but not necessarily all possible proxies on a network (e.g. corporate intranet situation).

When set we should look only at nth rightmost value and only check if it's unspecified or loopback to reject - private is fine.

2025-02-09 21:15 UTC, adam-p requested changes

2025-02-09 21:15 UTC, adam-p commented on middleware/client_ip.go
> +				}
I don't think the loopback/private/unspecified checks should be here at all. The user has specified that they trust certain reverse proxies, and I don't think we should have code here that second-guesses that. I think the first non-trusted IP should be returned regardless of what it is.

I would even prefer that there not be a check for IP validity at all (i.e., the netip.ParseAddr) call above, but it's obviously necessary for prefix checking. If the parse fails, I think it should trigger an error condition and not just be skipped.

These kinds of bad/incorrect IP failures indicate a configuration error. Which is pretty bad!

I'm even not sure I like "don't store the IP" as the way to handle error states. Panicking by default is unpalatable (although that's how I prefer to handle developer/configuration errors). Maybe there can be a flag or callback or something? I don't feel super strongly about it, though.

2025-02-09 21:15 UTC, adam-p commented on middleware/client_ip.go
> +			if err != nil || ip.IsLoopback() || ip.IsUnspecified() || ip.IsPrivate() {
For the same reasons as I mention in reply to @c2h5oh's comment below, I don't think these checks should be here at all. (In short: The user has said this is trustworthy and we should treat it as such.)

2025-02-09 21:15 UTC, adam-p commented on middleware/client_ip.go
> +// The middleware ignores invalid or private IPs.
As above: Why? The user has indicated that this is the value they want.

But also... I don't think you're actually doing the loopback/private/unspecified check here, so I don't think this comment is true?

2025-02-09 21:15 UTC, adam-p commented on middleware/client_ip.go
> +	if !ok || !ip.IsValid() {
Depending on above discussions, the ip.IsValid check might not be right.

2025-02-09 21:15 UTC, adam-p commented on middleware/client_ip_test.go
> +	tt := []struct {
I would prefer to see tests that exercise the trusted range functionality.

2025-06-19 15:49 UTC, c2h5oh commented on middleware/client_ip.go
> +				}
You will get private IPs here e.g. if you use nginx ingress in k8s

2025-06-21 14:46 UTC, adam-p commented on middleware/client_ip.go
> +				}
Shouldn't it be on the user to know that and put the ingress IP prefixes in `trustedIPPrefixes`?

2026-02-01 18:05 UTC, rezmoss commented
test cases ip spoofing (feel free to edit/delete)
```
// TestClientIPFromXFFHeaderWithTrustedPrefixes tests the trusted CIDR prefix
func TestClientIPFromXFFHeaderWithTrustedPrefixes(t *testing.T) {
	tt := []struct {
		name            string
		xff             []string
		trustedPrefixes []string
		expected        string
	}{
		// single trusted proxy, proxy ip should be skipped
		{
			name:            "single_trusted_proxy",
			xff:             []string{"8.8.8.8, 203.0.113.50"},
			trustedPrefixes: []string{"203.0.113.0/24"},
			expected:        "8.8.8.8",
		},
		// multiple trusted proxies chain
		{
			name:            "multiple_trusted_proxies",
			xff:             []string{"1.1.1.1, 203.0.113.10, 198.51.100.5"},
			trustedPrefixes: []string{"203.0.113.0/24", "198.51.100.0/24"},
			expected:        "1.1.1.1",
		},
		// all ipss in trusted range,should return empty (no untrusted client)
		{
			name:            "all_ips_trusted",
			xff:             []string{"203.0.113.10, 203.0.113.20"},
			trustedPrefixes: []string{"203.0.113.0/24"},
			expected:        "",
		},
		// ipv6 trusted range e.g. cloudflare
		{
			name:            "ipv6_trusted_range",
			xff:             []string{"2001:db8::1, 2606:4700::1"},
			trustedPrefixes: []string{"2606:4700::/32"},
			expected:        "2001:db8::1",
		},
		// mixed ip and ipv6 trusted ranges
		{
			name:            "mixed_ipv4_ipv6_trusted",
			xff:             []string{"8.8.8.8, 2606:4700::1, 203.0.113.5"},
			trustedPrefixes: []string{"2606:4700::/32", "203.0.113.0/24"},
			expected:        "8.8.8.8",
		},
		// trusted prefix with longer chain
		{
			name:            "long_proxy_chain",
			xff:             []string{"1.2.3.4, 5.6.7.8, 203.0.113.1, 198.51.100.1"},
			trustedPrefixes: []string{"203.0.113.0/24", "198.51.100.0/24"},
			expected:        "5.6.7.8",
		},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			req, _ := http.NewRequest("GET", "/", nil)
			for _, v := range tc.xff {
				req.Header.Add("X-Forwarded-For", v)
			}
			w := httptest.NewRecorder()

			r := chi.NewRouter()
			r.Use(ClientIPFromXFFHeader(tc.trustedPrefixes...))

			var clientIP string
			r.Get("/", func(w http.ResponseWriter, r *http.Request) {
				clientIP = GetClientIP(r.Context())
				w.Write([]byte("OK"))
			})
			r.ServeHTTP(w, req)

			if clientIP != tc.expected {
				t.Errorf("expected %q, got %q", tc.expected, clientIP)
			}
		})
	}
}

// TestXFFSpoofingPrevention tests ip spoofing attack scenarios in X-Forwarded-For context
func TestXFFSpoofingPrevention(t *testing.T) {
	tt := []struct {
		name            string
		xff             []string
		trustedPrefixes []string
		expected        string
		description     string
	}{
		{
			name:        "prepend_spoofed_loopback",
			xff:         []string{"127.0.0.1, 8.8.8.8"},
			expected:    "8.8.8.8",
			description: "Spoofed loopback ignored, real IP returned",
		},
		{
			name:        "prepend_spoofed_private",
			xff:         []string{"10.0.0.1, 8.8.8.8"},
			expected:    "8.8.8.8",
			description: "Spoofed private IP ignored, real IP returned",
		},
		// attacker prepends spoofed ip w trusted proxy in chain
		{
			name:            "spoof_with_trusted_proxy",
			xff:             []string{"127.0.0.1, 203.0.113.50, 198.51.100.1"},
			trustedPrefixes: []string{"198.51.100.0/24"},
			expected:        "203.0.113.50",
			description:     "Proxy skipped, spoofed loopback ignored, client IP returned",
		},
		// multiple xff headers,attacker injects first header
		{
			name:            "multi_header_injection_with_proxy",
			xff:             []string{"127.0.0.1", "8.8.8.8, 198.51.100.1"},
			trustedPrefixes: []string{"198.51.100.0/24"},
			expected:        "8.8.8.8",
			description:     "Attacker's header ignored, proxy chain processed correctly",
		},
		{
			name:        "multi_header_injection_loopback",
			xff:         []string{"127.0.0.1", "8.8.8.8"},
			expected:    "8.8.8.8",
			description: "Attacker injects loopback in separate header",
		},
		// rate limit bypass prevention,spoofed ipsshould be ignored
		{
			name:            "rate_limit_bypass_attempt",
			xff:             []string{"attacker.spoofed.ip, 8.8.8.8, 198.51.100.1"},
			trustedPrefixes: []string{"198.51.100.0/24"},
			expected:        "8.8.8.8",
			description:     "Invalid spoofed IP ignored, consistent client IP for rate limiting",
		},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			req, _ := http.NewRequest("GET", "/", nil)
			for _, v := range tc.xff {
				req.Header.Add("X-Forwarded-For", v)
			}
			w := httptest.NewRecorder()

			r := chi.NewRouter()
			r.Use(ClientIPFromXFFHeader(tc.trustedPrefixes...))

			var clientIP string
			r.Get("/", func(w http.ResponseWriter, r *http.Request) {
				clientIP = GetClientIP(r.Context())
				w.Write([]byte("OK"))
			})
			r.ServeHTTP(w, req)

			if clientIP != tc.expected {
				t.Errorf("%s: expected %q, got %q", tc.description, tc.expected, clientIP)
			}
		})
	}
}

// TestClientIPMiddlewareChaining verifies that the first middleware to set
func TestClientIPMiddlewareChaining(t *testing.T) {
	t.Run("header_before_xff", func(t *testing.T) {
		req, _ := http.NewRequest("GET", "/", nil)
		req.Header.Set("CF-Connecting-IP", "1.1.1.1")
		req.Header.Set("X-Forwarded-For", "2.2.2.2")
		w := httptest.NewRecorder()

		r := chi.NewRouter()
		r.Use(ClientIPFromHeader("CF-Connecting-IP"))
		r.Use(ClientIPFromXFFHeader())

		var clientIP string
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			clientIP = GetClientIP(r.Context())
			w.Write([]byte("OK"))
		})
		r.ServeHTTP(w, req)

		expected := "1.1.1.1"
		if clientIP != expected {
			t.Errorf("expected %q (from header), got %q", expected, clientIP)
		}
	})

	t.Run("xff_before_remoteaddr", func(t *testing.T) {
		req, _ := http.NewRequest("GET", "/", nil)
		req.Header.Set("X-Forwarded-For", "8.8.8.8")
		req.RemoteAddr = "192.0.2.1:1234"
		w := httptest.NewRecorder()

		r := chi.NewRouter()
		r.Use(ClientIPFromXFFHeader())
		r.Use(ClientIPFromRemoteAddr)

		var clientIP string
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			clientIP = GetClientIP(r.Context())
			w.Write([]byte("OK"))
		})
		r.ServeHTTP(w, req)

		expected := "8.8.8.8"
		if clientIP != expected {
			t.Errorf("expected %q (from XFF), got %q", expected, clientIP)
		}
	})

	t.Run("empty_header_falls_through", func(t *testing.T) {
		req, _ := http.NewRequest("GET", "/", nil)
		req.Header.Set("X-Forwarded-For", "8.8.8.8")
		w := httptest.NewRecorder()

		r := chi.NewRouter()
		r.Use(ClientIPFromHeader("CF-Connecting-IP"))
		r.Use(ClientIPFromXFFHeader())

		var clientIP string
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			clientIP = GetClientIP(r.Context())
			w.Write([]byte("OK"))
		})
		r.ServeHTTP(w, req)

		expected := "8.8.8.8"
		if clientIP != expected {
			t.Errorf("expected %q (from XFF fallback), got %q", expected, clientIP)
		}
	})

	t.Run("private_header_falls_through", func(t *testing.T) {
		req, _ := http.NewRequest("GET", "/", nil)
		req.Header.Set("X-Real-IP", "192.168.1.1") // private ignoredd
		req.Header.Set("X-Forwarded-For", "8.8.8.8")
		w := httptest.NewRecorder()

		r := chi.NewRouter()
		r.Use(ClientIPFromHeader("X-Real-IP"))
		r.Use(ClientIPFromXFFHeader())

		var clientIP string
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			clientIP = GetClientIP(r.Context())
			w.Write([]byte("OK"))
		})
		r.ServeHTTP(w, req)

		expected := "8.8.8.8"
		if clientIP != expected {
			t.Errorf("expected %q (XFF after private rejected), got %q", expected, clientIP)
		}
	})
}

// TestPrivateIPWithTrustedPrefixes Should IsPrivate()/IsLoopback() checks be dropped when trusted prefixes are configured based  adam-p blog
func TestPrivateIPWithTrustedPrefixes(t *testing.T) {
	tt := []struct {
		name            string
		xff             string
		trustedPrefixes []string
		currentResult   string
		proposedResult  string
		description     string
	}{
		// k8s pod to pod: both ip are pri [...]

2026-05-17 12:31 UTC, VojtechVitek commented
Thanks everyone for the thorough reviews and feedback on this PR. I've been figuring out how to work through it all — the comments, open advisories, and decisions needed. With a bit of help from Opus 4.7, I've worked through everything and landed on a plan. Give it a read and let me know if anything stands out.
I'll execute on the plan and have a final commit ready to merge.

---

# PR #967 — ClientIP middleware: Plan to finish

A plan to address the open review feedback on
[PR #967](https://github.com/go-chi/chi/pull/967), close out the three
published security advisories against `middleware.RealIP`, and land a
small, safe, easy-to-use `ClientIP*` middleware family.

---

## Why this matters — three open advisories

Chi currently has **three published security advisories**, all
targeting the same root cause: `middleware.RealIP` blindly trusts
client-supplied headers.

| Advisory | Reporter | Severity | Status |
|---|---|---|---|
| [GHSA-9g5q-2w5x-hmxf](https://github.com/go-chi/chi/security/advisories/GHSA-9g5q-2w5x-hmxf) — IP spoofing via XFF in `RemoteAddr` resolution | convto | Moderate | Unpatched |
| [GHSA-rjr7-jggh-pgcp](https://github.com/go-chi/chi/security/advisories/GHSA-rjr7-jggh-pgcp) — RealIP allows IP spoofing via unvalidated XFF | rezmoss | Moderate | Unpatched |
| [GHSA-3fxj-6jh8-hvhx](https://github.com/go-chi/chi/security/advisories/GHSA-3fxj-6jh8-hvhx) — IP spoofing in `middleware.RealIP` | Saku0512 | **Critical (9.3)** | Unpatched |

All three reporters propose the same fix shape: rightmost-untrusted
traversal of `X-Forwarded-For` with an explicit trusted-CIDR list.
That is exactly what `ClientIPFromXFF` does (renamed from
`ClientIPFromXFFHeader` in this PR).

**This PR is the patch for all three advisories** and the
deprecation of `middleware.RealIP` is part of that patch.

---

## What the source-of-truth references say

[adam-p's "The perils of the 'real' client IP"](https://adam-p.ca/blog/2022/03/x-forwarded-for/)
is the definitive write-up. The points that drive our API:

1. **Rightmost-ish, never leftmost.** Leftmost is trivially spoofable.
2. **There's no sane default — so there should be no default.** The
   blog calls out chi by name on this. ("Conclusion #4")
3. **Defaults must not be insecure.** No auto-fall-back through a
   list of headers an attacker could supply. ("Conclusion #5")
4. **Any header you trust must be set/overwritten by your own
   infrastructure for every request** — otherwise it's
   attacker-controlled.
5. **Multiple `X-Forwarded-For` headers must be merged**, not just
   `Header.Get()`-ed.
6. **Behind multiple proxies, you need either trusted-proxy
   IPs/prefixes OR a trusted-proxy count** (rightmost-ish algorithm).
7. **`RemoteAddr` can be `ip:port`** — split correctly.
8. **Re-fronting attack** — even a "trusted" CDN IP can be
   attacker-controlled if a third-party distribution points at your
   origin. Mitigation is out-of-band (shared secret / client cert at
   the origin). Out of scope to fix in middleware; doc warning only.
9. **`Forwarded` (RFC 7239) has the same problems** and almost
   nobody uses it. Skip.

---

## Summary of reviewer feedback on PR #967

### c2h5oh (CHANGES_REQUESTED)

1. **`client_ip.go` L112** — when `trustedIPPrefixes` is set, the
   `IsLoopback / IsPrivate / IsUnspecified` rejection inside the XFF
   loop is wrong: "no loopback, private or unspecified addresses
   should exist past/in between trusted prefixes unless headers have
   been tampered with."
2. (Jun 2025) **Real-world hit**: nginx-ingress in k8s legitimately
   produces private IPs in the chain — the current code skips them
   and breaks lookups.
3. **New API idea**: a trusted-proxy-count knob (Traefik-style) for
   the case where you control exactly N proxies but not all possible
   proxies on a corporate network.

### adam-p (CHANGES_REQUESTED)

1. **L32 godoc** — `X-Azure-ClientIP`, `True-Client-IP`,
   `Fastly-Client-IP` are NOT trustworthy headers per his blog and
   shouldn't be listed as such.
2. **L46 and L112** — drop all the `IsLoopback / IsPrivate /
   IsUnspecified` second-guessing in both `ClientIPFromHeader` and
   `ClientIPFromXFFHeader`. The user has explicitly said what to
   trust; we shouldn't override that.
3. **L112** — a `ParseAddr` failure mid-chain indicates a
   configuration error; it shouldn't be silently skipped. Suggests
   an error / flag / callback (no strong preference).
4. **L137 godoc** (`ClientIPFromRemoteAddr`) — comment claims it
   "ignores invalid or private IPs", but it doesn't.
5. **L181 `GetClientIP`** — `ip.IsValid()` check may be redundant if
   we drop second-guessing.
6. **L73 tests** — add tests that exercise the trusted-range
   functionality.
7. (Jun 2025) Reaffirms: even nginx-ingress private IPs should be
   configured by the user via `trustedIPPrefixes`, not auto-filtered.

### rezmoss (proposed tests on PR #967)

Four ready-to-paste test functions:

- `TestClientIPFromXFFHeaderWithTrustedPrefixes` — CIDR behavior incl.
  IPv6, mixed v4/v6, long chains.
- `TestXFFSpoofingPrevention` — rightmost-untrusted defeats spoofing.
- `TestClientIPMiddlewareChaining` — header → xff → remoteaddr
  fallthrough.
- `TestPrivateIPWithTrustedPrefixes` — k8s, nginx, AWS internal LB.

### Saku0512 (follow-up [PR #1087](https://github.com/go-chi/chi/pull/1087) on top of #967)

Adds `TestClientIPFromXFFHeaderWithTrustedPrefixes` with boundary
tests: `.0` and `.255` of a `/24`, IP just outside, all-trusted →
empty, no-prefixes baseline. **Cleanly aligned with our API.** We
pull these in (or merge #1087 once we've landed the core changes).

### Convergence

Both blocking reviewers and all three advisory reporters
(rezmoss explicitly, convto and Saku0512 by algorithm) converge on
one thing: **stop second-guessing the user**. Drop the
`IsPrivate / IsLoopback / IsUnspecified` rejection and let the
explicit trust list be authoritative. This also unblocks the
legitimate k8s / nginx-ingress / internal-LB cases.

---

## Is the API right?

Final surface for this PR:

```go
// Trust a single-IP header set by your infrastructure.
func ClientIPFromHeader(trustedHeader string) func(http.Handler) http.Handler

// Trust XFF, walking right-to-left and skipping the listed trusted CIDRs.
// Zero args ⇒ rightmost parseable IP (safe only behind one trusted hop).
func ClientIPFromXFF(trustedIPPrefixes ...string) func(http.Handler) http.Handler

// Trust XFF, knowing the exact number of trusted proxies in front of you.
// Returns xff[len-numTrustedProxies], or empty if XFF has fewer entries.
// Panics if numTrustedProxies < 1.
func ClientIPFromXFFTrustedProxies(numTrustedProxies int) func(http.Handler) http.Handler

// Trust the TCP RemoteAddr (only safe when directly connected to the internet).
func ClientIPFromRemoteAddr(h http.Handler) http.Handler

// Accessors.
func GetClientIP(ctx context.Context) string         // empty if not set
func GetClientIPAddr(ctx context.Context) netip.Addr // zero value if not set
```

Scored against the blog + advisory checklist:

| Requirement | Status |
|---|---|
| Rightmost-untrusted algorithm | ✅ `ClientIPFromXFF` |
| No default header fallback list | ✅ separate middlewares; user composes |
| Merge multiple XFF headers | ✅ `Header.Values("X-Forwarded-For")` joined |
| Trusted CIDRs / IPs | ✅ variadic `trustedIPPrefixes ...string` |
| Trusted-proxy-COUNT alternative (Traefik-style) | ✅ `ClientIPFromXFFTrustedProxies(n)` |
| Validate before parsing | ✅ via `netip.ParseAddr` |
| Don't mutate `RemoteAddr` | ✅ context-based |
| Doesn't second-guess what the user trusts | 🟡 still rejects private/loopback — dropped in Phase 1 |
| Typed accessor for `netip.Addr` | ✅ `GetClientIPAddr(ctx)` |
| Strong security warnings in godoc | 🟡 insufficient — expanded in Phase 1 |
| Misleading "trusted" header examples | 🟡 lists Akamai/Azure/Fastly — removed in Phase 1 |
| Document re-fronting / dual-connection / network-change risks | ❌ added in Phase 1 |

**Why two XFF functi [...]

2026-05-17 13:32 UTC, VojtechVitek commented
@c2h5oh @adam-p @Saku0512 please review :)

2026-05-18 13:15 UTC, Saku0512 requested changes
Requesting changes for one documentation issue that can lead to incorrect client IP selection in real deployments. The implementation looks good, but the fallback ordering guidance for `ClientIPFromXFFTrustedProxies` appears reversed for chi's middleware execution order.

2026-05-18 13:15 UTC, Saku0512 commented on middleware/client_ip.go
> +// after this middleware if you want a fallback.
Should this say to register `ClientIPFromRemoteAddr` **before** this middleware?

In chi, middlewares run in registration order, and each `ClientIPFrom*` middleware overwrites the context value when it finds a valid IP. If users follow the current "after this middleware" guidance, `ClientIPFromRemoteAddr` runs later and overwrites a valid XFF-derived client IP with the immediate peer address.

For fallback behavior, the safe order should be fallback first, preferred source last:

```go
r.Use(middleware.ClientIPFromRemoteAddr)
r.Use(middleware.ClientIPFromXFFTrustedProxies(2))
```

That way RemoteAddr is used only when XFF does not produce a client IP.

2026-05-18 14:27 UTC, VojtechVitek commented on middleware/client_ip.go
> +// after this middleware if you want a fallback.
Good catch on the inverted order — but rather than reverse the example, I've dropped the fallback-chaining note entirely. The whole point of 482e855 was to push users to pick exactly one ClientIPFrom* middleware; documenting a chaining recipe here works against that. The honest answer when XFF is too short is just GetClientIP() == "", and the caller decides what to do.

Thank you 👍

2026-05-18 14:31 UTC, Saku0512 approved these changes

2026-05-18 14:32 UTC, VojtechVitek commented on middleware/client_ip.go
> +// after this middleware if you want a fallback.
Addressed in 7ca76eecd95a36161f7ac48e5f3c14e46197d5b5.

Appreciate your help 🙏 🙌

2026-05-18 14:39 UTC, Saku0512 commented on middleware/client_ip.go
> +// after this middleware if you want a fallback.
thanks!!

2026-05-21 00:46 UTC, VojtechVitek commented
## Threat model coverage

| Advisory | Root cause in `RealIP` | How this PR closes it |
|---|---|---|
| [GHSA-3fxj-6jh8-hvhx](https://github.com/go-chi/chi/security/advisories/GHSA-3fxj-6jh8-hvhx) | Trusts arbitrary client-supplied headers | User explicitly picks one source; rightmost-untrusted on XFF; bare TCP peer for direct-internet |
| [GHSA-rjr7-jggh-pgcp](https://github.com/go-chi/chi/security/advisories/GHSA-rjr7-jggh-pgcp) | Auto-fallback through True-Client-IP / X-Real-IP / XFF | No default; each `ClientIPFrom*` reads exactly one opted-in source |
| [GHSA-9g5q-2w5x-hmxf](https://github.com/go-chi/chi/security/advisories/GHSA-9g5q-2w5x-hmxf) | Mutates `r.RemoteAddr` from leftmost XFF | Context-stored; rightmost-untrusted; `r.RemoteAddr` never mutated |

## adam-p blog checklist

Against [adam-p's "The perils of the 'real' client IP"](https://adam-p.ca/blog/2022/03/x-forwarded-for/):

| Requirement | Status |
|---|---|
| Rightmost-ish, never leftmost | ✅ |
| No safe default; no auto-fallback header list | ✅ |
| Trusted headers must be infra-overwritten | ✅ documented, traps named by product |
| Merge multiple XFF headers (RFC 2616) | ✅ |
| Single-IP header tolerates multi-value misconfig (last wins) | ✅ defense-in-depth |
| Trusted CIDRs *or* trusted-proxy count | ✅ both variants |
| `RemoteAddr` should be `ip:port` | ✅ |
| Don't mutate `r.RemoteAddr` | ✅ context-based |
| No private/loopback filtering (don't second-guess the user) | ✅ |
| Validate before parsing; fail-closed on garbage mid-chain | ✅ |
| Normalize v4-mapped IPv6 and IPv6 header zones | ✅ at every entry point |
| Typed accessor for `netip.Addr` | ✅ `GetClientIPAddr` |
| Re-fronting / dual-connection attack | 🟡 out of scope (firewall layer) |
| RFC 7239 `Forwarded` header | 🟡 deliberately skipped (same problems as XFF, almost no adoption) |

---

TL;DR: replaces `middleware.RealIP` with four orthogonal `ClientIPFrom*`
middlewares + two accessors. All three GHSAs closed and pinned by named
tests. `r.RemoteAddr` is never mutated. Migration recipes in README +
godoc.

2026-05-21 01:05 UTC, VojtechVitek commented on middleware/logger.go
> +	entry.buf.WriteString(clientIP)
Thanks — this is intentional, not a regression.

The format change is bounded to users who **opt in** to a `ClientIPFrom*`
middleware. For everyone else `GetClientIP(ctx)` returns `""` and we fall
back to `r.RemoteAddr`, preserving the existing `IP:port` shape exactly.

Users migrating from `middleware.RealIP` also see no Logger change: `RealIP`
already mutated `r.RemoteAddr` to a port-less XFF value (that's the
long-standing [#453](https://github.com/go-chi/chi/issues/453)), so their
`from` field was already IP-only.

Forcing `IP:port` on the new path would mean either fabricating a port
(misleading) or pasting `r.RemoteAddr`'s port — which is the *immediate
proxy hop's* TCP source port, not the client's — onto the client IP. That's
actively wrong for any downstream parser that reads the port.

Custom formatters that genuinely need a stable composite shape can always
compose it explicitly: `GetClientIP(r.Context())` + `r.RemoteAddr`.

2026-05-21 08:39 UTC, VojtechVitek commented
Thanks @copilot.

- **`Header.Get` → last `Values()`** is a real defense-in-depth gap; fixed
  in `a8e3dbf` after pinning the four bypass shapes with failing tests in
  `22f567f`.
- **Godoc inconsistency on `ClientIPFromXFF()` no-args** fixed in `e692997`.
- **O(n²) walkXFF claim** — pushing back with a benchmark
(`5684b03`):
```
BenchmarkWalkXFF/n=1          5.6 ns/op
BenchmarkWalkXFF/n=10        57.6 ns/op    (5.8 ns/entry)
BenchmarkWalkXFF/n=100      541.1 ns/op    (5.4 ns/entry)
BenchmarkWalkXFF/n=1000    5228   ns/op    (5.2 ns/entry)
BenchmarkWalkXFF/n=10000  55148   ns/op    (5.5 ns/entry)
BenchmarkWalkXFF_RightmostStop/n=10000   6.1 ns/op   -- truly constant
```

2026-05-21 09:03 UTC, VojtechVitek commented on middleware/client_ip.go
> +				if ip, ok := parseHeaderAddr(values[len(values)-1]); ok {
Empirically verified: Go's `net/http.ReadRequest` strips leading AND
trailing OWS (spaces and tabs) from header values during wire parsing.
Six variations tested including double-whitespace and tab cases, all
produce a clean stored value. So for production traffic the concern is
moot. Programmatic injection via `r.Header.Add(key, " value ")` is the
only path that preserves the OWS, and that's user-code responsibility
(test fixtures, custom adapters). Leaving the trim out keeps the hot
path strictly minimal.

2026-05-21 09:06 UTC, VojtechVitek commented
Thanks to Copilot and Claude for additional hardening of this PR.

This PR is now ready for final human reviews & merge. ✅

2026-05-21 14:19 UTC, rezmoss commented
@VojtechVitek  one thing before mrg, middleware.realip itself is unchanged, i verified that x-forwarded-for 127.0.0.1 still spoofs r.remoteaddr, if these three gh get a "patched version", govulncheck & dependabot will mark every chi ver after that release as safe, even though code still using middleware.realip remains fully exploitable, suggest keeping them as "no fix, realip deprecated, migrate to clientipfrom" instead of assigning a patched ver

2026-05-22 08:50 UTC, VojtechVitek commented
@rezmoss I've marked `middleware.RealIP` as deprecated in this PR. Anything else we can do here? We can't remove it from the go-chi package completely due to the semver compatibility promise.

2026-05-22 15:16 UTC, merged

2026-05-22 16:01 UTC, VojtechVitek commented
Released in https://github.com/go-chi/chi/releases/tag/v5.3.0

2026-05-23 15:51 UTC, rezmoss commented
@VojtechVitek could request cve plz

2026-07-13 11:10 UTC, scop commented
Website docs have not been updated per this yet, https://github.com/go-chi/docs/issues/18

2026-07-27 19:17 UTC, VojtechVitek commented
https://github.com/go-chi/docs/issues/18 fixed.

Next, I will work on httprate pkg update.